version: '3.8'

services:
  kali:
    build:
      context: .
      dockerfile: Dockerfile.kali
    container_name: huntforge-kali
    env_file:
      - .env
    volumes:
      - ./:/huntforge
      - ~/.huntforge:/root/.huntforge
    working_dir: /huntforge
    command: tail -f /dev/null
    restart: unless-stopped
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 128M
    networks:
      - huntforge



networks:
  huntforge:
    driver: bridge
